[package]
name = "radix-yew-use-size"
description = "Yew port of Radix Use Size."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
web-sys = { workspace = true, features = [
    "ResizeObserver",
    "ResizeObserverBoxOptions",
    "ResizeObserverEntry",
    "ResizeObserverOptions",
    "ResizeObserverSize",
] }
yew.workspace = true
