[workspace]
members = ["packages/colors", "packages/primitives/*/*", "scripts", "stories/*"]
resolver = "2"

[workspace.package]
authors = ["Rust For Web <info@rustforweb.org>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/RustForWeb/radix"
version = "0.0.1"

[workspace.dependencies]
console_log = "1.0.0"
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.12" }
leptos_router = { version = "0.6.12" }
log = "0.4.21"
tailwind_fuse = { version = "0.3.0", features = ["variant"] }
web-sys = "0.3.69"
