[package]
name = "radix-dioxus-slot"
description = "Dioxus port of Radix Slot."
homepage = "https://radix.rustforweb.org/primitives/utilities/slot.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dioxus.workspace = true
log.workspace = true
