[package]
name = "radix-yew-label"
description = "Yew port of Radix Label."
homepage = "https://radix.rustforweb.org/primitives/components/label.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
radix-yew-primitive = { path = "../primitive", version = "0.0.2" }
web-sys.workspace = true
yew.workspace = true
yew-attrs.workspace = true
