[book]
authors = ["Daniëlle Huisman"]
language = "en"
multilingual = false
src = "src"
title = "Rust Radix"

[preprocessor.tabs]

[preprocessor.trunk]

[output.html]
additional-css = ["theme/tabs.css", "theme/theme.css"]
additional-js = ["theme/tabs.js"]

[output.trunk]
serve = true

[rust]
edition = "2021"
